### ISSUE TITLE
Error opening a series

### ISSUE THREAD

**Issue by myenji** [MrKrabat/plugin.video.wakanim#19]
Hello, when I want to open the list of episodes of a series, I have an error.
I use Kodi (18.4 Git: leia_pi4_18.4-Leia). Platform: Linux ARM 32-bit
it did not work overnight, I can not unfortunately say what caused this.
Here are the logs:

>2019-10-09 23:34:47.570 T:2582922096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.wakanim/default.py", line 35, in <module>
                                                wakanim.main(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.wakanim/resources/lib/wakanim.py", line 70, in main
                                                check_mode(args)
                                              File "/storage/.kodi/addons/plugin.video.wakanim/resources/lib/wakanim.py", line 107, in check_mode
                                                controller.listSeason(args)
                                              File "/storage/.kodi/addons/plugin.video.wakanim/resources/lib/controller.py", line 337, in listSeason
                                                year = date[2].string.strip()
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

I do not know if I am the only one or not, but thank you in advance for any help or advice

(yes I use google trad, I'm sorry :confused: )

**Comment by petersen77** [comment]
Any news?

**Comment by MrKrabat** [comment]
I pushed a fix for this.

You can install it manually or wait a couple of days until this patch is merged into the Kodi repository.

**Comment by myenji** [comment]
It works ! Thank you for taking the trouble to patch :)
