### ISSUE TITLE
[BUG] Can't open a Series.

### ISSUE THREAD

**Issue by kev-dev1** [MrKrabat/plugin.video.wakanim#20]
On Kodi 18.4 come a error, when i open a series. The Addon ist the last version from Kodi Repo.
The error log come from Kodi.log:

2019-11-03 18:36:32.850 T:139621146339072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/kevtolka/.kodi/addons/plugin.video.wakanim/default.py", line 35, in <module>
                                                wakanim.main(sys.argv)
                                              File "/home/kevtolka/.kodi/addons/plugin.video.wakanim/resources/lib/wakanim.py", line 70, in main
                                                check_mode(args)
                                              File "/home/kevtolka/.kodi/addons/plugin.video.wakanim/resources/lib/wakanim.py", line 107, in check_mode
                                                controller.listSeason(args)
                                              File "/home/kevtolka.kodi/addons/plugin.video.wakanim/resources/lib/controller.py", line 337, in listSeason
                                                year = date[2].string.strip()
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by kev-dev1** [comment]
The new Plugin Update not working for open a Series from Katalog
