### ISSUE TITLE
Cannot view Catalog

### ISSUE THREAD

**Issue by d4nl** [MrKrabat/plugin.video.wakanim#26]
- Running on latest master from this git repo.
- Works without any problems via webbrowser but not via plugin.
- Other main options such as Last aired, Last simulcast work.

Error:
```
2020-02-28 11:08:02.780 T:140526117693184   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.wakanim/default.py", line 35, in <module>
                                                wakanim.main(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.wakanim/resources/lib/wakanim.py", line 70, in main
                                                check_mode(args)
                                              File "/storage/.kodi/addons/plugin.video.wakanim/resources/lib/wakanim.py", line 93, in check_mode
                                                controller.showCatalog(args)
                                              File "/storage/.kodi/addons/plugin.video.wakanim/resources/lib/controller.py", line 76, in showCatalog
                                                "plot":        plot.contents[3].string.strip(),
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-02-28 11:08:02.865 T:140527326435072   ERROR: GetDirectory - Error getting plugin://plugin.video.wakanim/?mode=catalog&title=Catalog
2020-02-28 11:08:02.866 T:140528689331840   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.wakanim/?mode=catalog&title=Catalog) failed
```

**Comment by KyKyIIIKuH** [comment]
quick patch
/resources/lib/controller.py
Added line 61-69 and Edited line 86
[https://pastebin.com/31NMrq7H](url)

checked the error is gone

**Comment by montaropdf** [comment]
Hi,

As I am also suffering from the same problem, can you tell when the patch in [fix catalogue not working](https://github.com/MrKrabat/plugin.video.wakanim/pull/30) will be merged to master and available from kodi update interface?

Thank you for your effort.

**Comment by MrKrabat** [comment]
The latest update should reach you soon
