### ISSUE TITLE
IndexError: list index out of range, if I open mydownloads

### ISSUE THREAD

**Issue by Lukas1818** [MrKrabat/plugin.video.wakanim#35]
Every time I try to open "mydownloads" I get a IndexError:

```
2021-01-29 21:01:37.826 T:2256253808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.wakanim/default.py", line 35, in <module>
                                                wakanim.main(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.wakanim/resources/lib/wakanim.py", line 70, in main
                                                check_mode(args)
                                              File "/storage/.kodi/addons/plugin.video.wakanim/resources/lib/wakanim.py", line 103, in check_mode
                                                controller.myDownloads(args)
                                              File "/storage/.kodi/addons/plugin.video.wakanim/resources/lib/controller.py", line 215, in myDownloads
                                                html = api.getPage(args, "https://www.wakanim.tv/" + args._country + "/v2/mydownloads")
                                              File "/storage/.kodi/addons/plugin.video.wakanim/resources/lib/api.py", line 94, in getPage
                                                form = soup.find_all("form", {"class": "nav-user_login"})[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2021-01-29 21:01:37.937 T:2424304496   ERROR: GetDirectory - Error getting plugin://plugin.video.wakanim/?mode=downloads&title=Meine%20Downloads
2021-01-29 21:01:37.950 T:3011482960   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.wakanim/?mode=downloads&title=Meine%20Downloads) failed
```

**Comment by C4ET4uK** [comment]
same issue
but different url
looks like it depends on region
`2021-01-30 10:51:09.824 T:2631962832   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.wakanim/default.py", line 35, in <module>
                                                wakanim.main(sys.argv)
                                              File "/home/pi/.kodi/addons/plugin.video.wakanim/resources/lib/wakanim.py", line 70, in main
                                                check_mode(args)
                                              File "/home/pi/.kodi/addons/plugin.video.wakanim/resources/lib/wakanim.py", line 93, in check_mode
                                                controller.showCatalog(args)
                                              File "/home/pi/.kodi/addons/plugin.video.wakanim/resources/lib/controller.py", line 47, in showCatalog
                                                html = api.getPage(args, "https://www.wakanim.tv/" + args._country + "/v2/catalogue")
                                              File "/home/pi/.kodi/addons/plugin.video.wakanim/resources/lib/api.py", line 94, in getPage
                                                form = soup.find_all("form", {"class": "nav-user_login"})[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2021-01-30 10:51:09.871 T:2642116816   ERROR: GetDirectory - Error getting plugin://plugin.video.wakanim/?mode=catalog&title=%d0%9a%d0%b0%d1%82%d0%b0%d0%bb%d0%be%d0%b3
2021-01-30 10:51:09.901 T:2973162592   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.wakanim/?mode=catalog&title=%d0%9a%d0%b0%d1%82%d0%b0%d0%bb%d0%be%d0%b3) failed
`

**Comment by Lukas1818** [comment]
I could not test the other buttons, because I have no premium membership.

**Comment by KyKyIIIKuH** [comment]
does not work because Wakanim put Incapsula

https://github.com/MrKrabat/plugin.video.wakanim/issues/33

**Comment by MrKrabat** [comment]
As mentioned above, this addon unfortunately no longer works.
It will be removed from the Kodi addon repository shortly.
